import { COMMON_LABELS, COMMON_STATUS_OPTIONS } from '@/shared/constants';

export const OFFICE_LABELS = {
  LIST: {
    TITLE: 'Office',
    DESCRIPTION: 'Manage offices in the system',
    ADD_BUTTON: 'Tambah Office Baru',
    EMPTY: 'Tidak ada office ditemukan',
    COLUMNS: {
      CODE: COMMON_LABELS.FIELDS.CODE,
      NAME: 'Nama Office',
      TYPE: 'Type',
      COMPANY: 'Company',
      WORK_TIME: 'Jam Kerja',
      STATUS: COMMON_LABELS.FIELDS.STATUS,
      ACTIONS: COMMON_LABELS.FIELDS.ACTIONS,
    },
    STATUS: COMMON_LABELS.STATUS,
    ACTIONS: COMMON_LABELS.LIST.ACTIONS,
    FILTERS: {
      STATUS: COMMON_LABELS.FIELDS.STATUS,
    },
  },
  CREATE: {
    PAGE_TITLE: 'Buat Office Baru',
    BACK_BUTTON: COMMON_LABELS.ACTIONS.BACK,
    FIELDS: {
      CODE: `${COMMON_LABELS.FIELDS.CODE} Office`,
      NAME: `${COMMON_LABELS.FIELDS.NAME} Office`,
      TYPE: 'Type Office',
      PHONE: 'Telepon',
      COMPANY: 'Company',
      STATUS: COMMON_LABELS.FIELDS.STATUS,
      WORK_START_TIME: 'Jam Mulai',
      WORK_END_TIME: 'Jam Selesai',
      WORK_DAYS: 'Hari Kerja',
      LATITUDE: 'Latitude',
      LONGITUDE: 'Longitude',
      ATTENDANCE_RADIUS: 'Radius Absensi (meter)',
      TIMEZONE: 'Zona Waktu',
      PROVINCE: 'Provinsi',
      CITY: 'Kota',
      DISTRICT: 'Kecamatan',
      VILLAGE: 'Desa',
      ADDRESS_DETAIL: 'Detail Alamat',
      ADDRESS_SECTION: 'Informasi Alamat',
    },
    BUTTONS: {
      CANCEL: COMMON_LABELS.ACTIONS.CANCEL,
      SAVE: COMMON_LABELS.ACTIONS.SAVE,
      SAVING: COMMON_LABELS.STATE.SAVING,
    },
    DIALOG: {
      TITLE: 'Simpan Office Baru?',
      DESCRIPTION: 'Anda akan membuat office baru dengan data yang telah ditentukan.',
      CANCEL: COMMON_LABELS.ACTIONS.CANCEL,
      CONFIRM: COMMON_LABELS.ACTIONS.SAVE,
    },
  },
  EDIT: {
    PAGE_TITLE: 'Edit Office',
    BACK_BUTTON: COMMON_LABELS.ACTIONS.BACK,
    NOT_FOUND: 'Office tidak ditemukan',
    FIELDS: {
      CODE: COMMON_LABELS.FIELDS.CODE,
      NAME: COMMON_LABELS.FIELDS.NAME,
      TYPE: 'Type Office',
      PHONE: 'Telepon',
      COMPANY: 'Company',
      STATUS: COMMON_LABELS.FIELDS.STATUS,
      WORK_START_TIME: 'Jam Mulai',
      WORK_END_TIME: 'Jam Selesai',
      WORK_DAYS: 'Hari Kerja',
      LATITUDE: 'Latitude',
      LONGITUDE: 'Longitude',
      ATTENDANCE_RADIUS: 'Radius Absensi (meter)',
      TIMEZONE: 'Zona Waktu',
      PROVINCE: 'Provinsi',
      CITY: 'Kota',
      DISTRICT: 'Kecamatan',
      VILLAGE: 'Desa',
      ADDRESS_DETAIL: 'Detail Alamat',
      ADDRESS_SECTION: 'Informasi Alamat',
    },
    BUTTONS: {
      CANCEL: COMMON_LABELS.ACTIONS.CANCEL,
      SAVE: COMMON_LABELS.ACTIONS.SAVE_CHANGE,
      SAVING: COMMON_LABELS.STATE.SAVING,
    },
    DIALOG: {
      TITLE: 'Simpan Perubahan?',
      DESCRIPTION: 'Anda akan menyimpan perubahan pada office ini.',
      CANCEL: COMMON_LABELS.ACTIONS.CANCEL,
      CONFIRM: COMMON_LABELS.ACTIONS.SAVE,
    },
  },
  FORM: {
    TITLE: 'Office',
  },
  DIALOG: {
    DELETE_TITLE: 'Delete Office',
    DELETE_DESCRIPTION: 'Are you sure you want to delete this office?',
  },
  DETAIL: {
    PAGE_TITLE: 'Detail Office',
    BACK_BUTTON: COMMON_LABELS.ACTIONS.BACK,
    DELETE_BUTTON: COMMON_LABELS.ACTIONS.DELETE,
    EDIT_BUTTON: COMMON_LABELS.ACTIONS.EDIT,
    INFO_CARD_TITLE: 'Informasi Office',
    FIELDS: {
      CODE: COMMON_LABELS.FIELDS.CODE,
      NAME: 'Nama Office',
      TYPE: 'Type',
      COMPANY: 'Company',
      PHONE: 'Telepon',
      STATUS: COMMON_LABELS.FIELDS.STATUS,
      WORK_START_TIME: 'Jam Mulai',
      WORK_END_TIME: 'Jam Selesai',
      LATITUDE: 'Latitude',
      LONGITUDE: 'Longitude',
      ATTENDANCE_RADIUS: 'Radius Absensi (meter)',
      TIMEZONE: 'Zona Waktu',
      PROVINCE: 'Provinsi',
      CITY: 'Kota',
      DISTRICT: 'Kecamatan',
      VILLAGE: 'Desa',
      ADDRESS_DETAIL: 'Detail Alamat',
    },
    STATUS_ACTIVE: COMMON_LABELS.STATUS.ACTIVE,
    STATUS_INACTIVE: COMMON_LABELS.STATUS.INACTIVE,
    BUTTONS: {
      EDIT: COMMON_LABELS.ACTIONS.EDIT,
      CLOSE: COMMON_LABELS.ACTIONS.CANCEL,
    },
    DIALOG: {
      CHANGE_STATUS_TITLE: COMMON_LABELS.DIALOG.CHANGE_STATUS_TITLE,
      CHANGE_STATUS_DESCRIPTION: 'Anda akan mengubah status office ini.',
      CHANGE_STATUS_CANCEL: COMMON_LABELS.ACTIONS.CANCEL,
      CHANGE_STATUS_CONFIRM: COMMON_LABELS.ACTIONS.SAVE,
    },
  },
} as const;

export const STATUS_OPTIONS = COMMON_STATUS_OPTIONS;

export const OFFICE_TYPE_OPTIONS = [
  { label: 'Kantor Pusat', value: 'main_office' },
  { label: 'Kantor Cabang', value: 'branch_office' },
];

export const PLACEHOLDERS = {
  CODE: 'Masukan kode',
  NAME: 'Masukan nama office',
  TYPE: 'Pilih type office',
  PHONE: '',
  COMPANY: 'Pilih company',
  STATUS: COMMON_LABELS.PLACEHOLDERS.STATUS,
  WORK_START_TIME: '08:00',
  WORK_END_TIME: '17:00',
  LATITUDE: '0',
  LONGITUDE: '0',
  ATTENDANCE_RADIUS: '100',
  PROVINCE: 'Pilih provinsi',
  CITY: 'Pilih kota',
  DISTRICT: 'Pilih kecamatan',
  VILLAGE: 'Pilih desa',
  ADDRESS_DETAIL: 'Tulis detail alamat disini',
} as const;
