import { COMMON_LABELS, COMMON_STATUS_OPTIONS } from '@/shared/constants';

export const COMPANY_LABELS = {
  LIST: {
    TITLE: 'Company',
    DESCRIPTION: 'Manage companies in the system',
    ADD_BUTTON: 'Tambah Company Baru',
    EMPTY: 'Tidak ada company ditemukan',
    COLUMNS: {
      CODE: COMMON_LABELS.FIELDS.CODE,
      NAME: 'Nama Company',
      GROUP: 'Group',
      PROJECT_CAPABILITIES: 'Project Capabilities',
      STATUS: COMMON_LABELS.FIELDS.STATUS,
      ACTIONS: COMMON_LABELS.FIELDS.ACTIONS,
    },
    STATUS: COMMON_LABELS.STATUS,
    ACTIONS: COMMON_LABELS.LIST.ACTIONS,
    FILTERS: {
      STATUS: COMMON_LABELS.FIELDS.STATUS,
    },
  },
  CREATE: {
    PAGE_TITLE: 'Buat Company Baru',
    BACK_BUTTON: COMMON_LABELS.ACTIONS.BACK,
    FIELDS: {
      GROUP: 'Group',
      CODE: `${COMMON_LABELS.FIELDS.CODE} Company`,
      NAME: `${COMMON_LABELS.FIELDS.NAME} Company`,
      NPWP: 'NPWP',
      SIUP_NUMBER: 'Nomor SIUP',
      PROJECT_CAPABILITIES: 'Project Capabilities',
      PHONE: 'Telepon',
      EMAIL: 'Email',
      STATUS: COMMON_LABELS.FIELDS.STATUS,
      PROVINCE: 'Provinsi',
      CITY: 'Kota',
      DISTRICT: 'Kecamatan',
      VILLAGE: 'Kelurahan',

      ADDRESS_DETAIL: 'Detail Alamat',
      ADDRESS_SECTION: 'Informasi Alamat',
    },
    BUTTONS: {
      CANCEL: COMMON_LABELS.ACTIONS.CANCEL,
      SAVE: COMMON_LABELS.ACTIONS.SAVE,
      SAVING: COMMON_LABELS.STATE.SAVING,
    },
    DIALOG: {
      TITLE: 'Simpan Company Baru?',
      DESCRIPTION: 'Anda akan membuat company baru dengan data yang telah ditentukan.',
      CANCEL: COMMON_LABELS.ACTIONS.CANCEL,
      CONFIRM: COMMON_LABELS.ACTIONS.SAVE,
    },
  },
  EDIT: {
    PAGE_TITLE: 'Edit Company',
    BACK_BUTTON: COMMON_LABELS.ACTIONS.BACK,
    NOT_FOUND: 'Company tidak ditemukan',
    FIELDS: {
      GROUP: 'Group',
      CODE: COMMON_LABELS.FIELDS.CODE,
      NAME: COMMON_LABELS.FIELDS.NAME,
      NPWP: 'NPWP',
      SIUP_NUMBER: 'Nomor SIUP',
      PROJECT_CAPABILITIES: 'Project Capabilities',
      PHONE: 'Telepon',
      EMAIL: 'Email',
      STATUS: COMMON_LABELS.FIELDS.STATUS,
      PROVINCE: 'Provinsi',
      CITY: 'Kota',
      DISTRICT: 'Kecamatan',
      VILLAGE: 'Kelurahan',

      ADDRESS_DETAIL: 'Detail Alamat',
      ADDRESS_SECTION: 'Informasi Alamat',
    },
    BUTTONS: {
      CANCEL: COMMON_LABELS.ACTIONS.CANCEL,
      SAVE: COMMON_LABELS.ACTIONS.SAVE_CHANGE,
      SAVING: COMMON_LABELS.STATE.SAVING,
    },
    DIALOG: {
      TITLE: 'Simpan Perubahan?',
      DESCRIPTION: 'Anda akan menyimpan perubahan pada company ini.',
      CANCEL: COMMON_LABELS.ACTIONS.CANCEL,
      CONFIRM: COMMON_LABELS.ACTIONS.SAVE,
    },
  },
  FORM: {
    TITLE: 'Company',
  },
  DIALOG: {
    DELETE_TITLE: 'Delete Company',
    DELETE_DESCRIPTION: 'Are you sure you want to delete this company?',
  },
  DETAIL: {
    PAGE_TITLE: 'Detail Company',
    BACK_BUTTON: COMMON_LABELS.ACTIONS.BACK,
    DELETE_BUTTON: COMMON_LABELS.ACTIONS.DELETE,
    EDIT_BUTTON: COMMON_LABELS.ACTIONS.EDIT,
    INFO_CARD_TITLE: 'Informasi Company',
    DEPARTMENT_CARD_TITLE: 'Department',
    ADD_DEPARTMENT: 'Tambah',
    FIELDS: {
      CODE: COMMON_LABELS.FIELDS.CODE,
      NAME: 'Nama Company',
      GROUP: 'Group',
      NPWP: 'NPWP',
      SIUP_NUMBER: 'Nomor Surat Izin Usaha Perdagangan (SIUP)',
      PROJECT_CAPABILITIES: 'Project Capabilities',
      PHONE: 'Telepon',
      EMAIL: 'Email',
      STATUS: COMMON_LABELS.FIELDS.STATUS,
      PROVINCE: 'Provinsi',
      CITY: 'Kota',
      DISTRICT: 'Kecamatan',
      VILLAGE: 'Kelurahan',
      ADDRESS_DETAIL: 'Detail Alamat',
    },
    DEPARTMENT_COLUMNS: {
      CODE: COMMON_LABELS.FIELDS.CODE,
      NAME: 'Department',
      ACTION: COMMON_LABELS.FIELDS.ACTIONS,
    },
    STATUS_ACTIVE: COMMON_LABELS.STATUS.ACTIVE,
    STATUS_INACTIVE: COMMON_LABELS.STATUS.INACTIVE,
    BUTTONS: {
      EDIT: COMMON_LABELS.ACTIONS.EDIT,
      CLOSE: COMMON_LABELS.ACTIONS.CANCEL,
    },
    DIALOG: {
      CHANGE_STATUS_TITLE: COMMON_LABELS.DIALOG.CHANGE_STATUS_TITLE,
      CHANGE_STATUS_DESCRIPTION: 'Anda akan mengubah status company ini.',
      CHANGE_STATUS_CANCEL: COMMON_LABELS.ACTIONS.CANCEL,
      CHANGE_STATUS_CONFIRM: COMMON_LABELS.ACTIONS.SAVE,
      DELETE_DEPARTMENT_TITLE: 'Hapus Department',
      DELETE_DEPARTMENT_DESCRIPTION: 'Apakah anda yakin ingin menghapus department ini?',
      DELETE_DIALOG: {
        TITLE: 'Hapus Company?',
        DESCRIPTION: 'Anda akan menghapus company ini secara permanen.',
        CANCEL: COMMON_LABELS.ACTIONS.CANCEL,
        CONFIRM: COMMON_LABELS.ACTIONS.DELETE,
      },
    },
    NOT_FOUND: 'Company tidak ditemukan',
    EMPTY_DEPARTMENT: 'Tidak ada department',
  },
  ADD_DEPARTMENT: {
    TITLE: 'Tambah Department',
    FIELD_LABEL: 'Department',
    PLACEHOLDER: 'Pilih department',
    SAVE: COMMON_LABELS.ACTIONS.SAVE,
    CANCEL: COMMON_LABELS.ACTIONS.CANCEL,
  },
} as const;

export const STATUS_OPTIONS = COMMON_STATUS_OPTIONS;

export const PLACEHOLDERS = {
  GROUP: 'Pilih group',
  CODE: 'Masukan kode',
  NAME: 'Masukan nama company',
  NPWP: 'Masukan NPWP',
  SIUP_NUMBER: 'Masukan Nomor SIUP',
  PROJECT_CAPABILITIES: 'Pilih project capabilities',
  PHONE: '',
  EMAIL: 'Masukan email',
  STATUS: COMMON_LABELS.PLACEHOLDERS.STATUS,
  PROVINCE: 'Pilih provinsi',
  CITY: 'Pilih kota',
  DISTRICT: 'Pilih kecamatan',
  VILLAGE: 'Pilih kelurahan',
  ADDRESS_DETAIL: 'Tulis detail alamat disini',
} as const;
