export const SCURVE_ACTUAL_LINE_ADJUSTMENT_ENABLED = false;

export const DASHBOARD_LABELS = {
  GREETING: 'Selamat Datang',
  ROLE_LABEL: 'Role',
  ROLE_FALLBACK: '-',
  SCURVE: {
    TITLE: 'S-Curve Project',
    TOGGLE_WEEKLY: 'Weekly',
    TOGGLE_MONTHLY: 'Monthly',
    SERIES_ORIGINAL_PLAN: 'Original Plan (%)',
    SERIES_CURRENT_PLAN: 'Current Plan (%)',
    SERIES_ACTUAL: 'Actual (%)',
    TABLE_EMPTY_VALUE: '-',
  },
  COMMON: {
    ERROR_TITLE: 'Gagal memuat data dashboard',
    ERROR_DESCRIPTION: 'Terjadi kesalahan saat memuat section ini.',
    ERROR_RETRY: 'Coba lagi',
    UNAVAILABLE_TITLE: 'Company context is missing',
    UNAVAILABLE_DESCRIPTION:
      'Dashboard membutuhkan company aktif untuk memanggil API contract. Periksa query param `companyId` atau company switcher yang dipakai aplikasi.',
    NO_ACTIVE_PROJECT: 'No active project',
    OF_ACTIVE_PROJECTS: 'of active projects',
    POTENTIAL_VALUE_SUFFIX: 'potential value',
    ACTIVE_VALUE_SUFFIX: 'active value',
    COMPLETED_VALUE_SUFFIX: 'completed value',
    OF_RAB_SUFFIX: 'of RAB',
    USED_SUFFIX: 'used',
    AVAILABLE_SUFFIX: 'available',
    USED_LABEL: 'used',
    REMAINING_LABEL: 'remaining',
    PLANNED: 'Planned',
    ACTUAL: 'Actual',
    VARIANCE: 'Variance',
    STATUS: 'Status',
  },
  PROJECT_SUMMARY: {
    TITLE: 'Project Summary',
    DESCRIPTION:
      'Ringkasan portfolio, biaya, dan KPI dari seluruh project yang dimiliki perusahaan.',
    COMPANY_PLACEHOLDER: 'Company',
    METRIC_PROSPECT: 'Prospect',
    METRIC_ACTIVE: 'Active',
    METRIC_ATTENTION: 'Attention',
    METRIC_DELAYED: 'Delayed',
    METRIC_COMPLETED: 'Completed',
  },
  PORTFOLIO_PROGRESS: {
    TITLE: 'Portfolio Progress',
    DESCRIPTION:
      'Planned, actual, variance, dan status project dihitung dari seluruh project yang dimiliki perusahaan.',
    METRIC_PLANNED: 'Planned Progress',
    METRIC_ACTUAL: 'Actual Progress',
    METRIC_VARIANCE: 'Variance',
    METRIC_STATUS: 'Status',
    DETAIL_PLANNED: 'Linear BOQ schedule',
    DETAIL_ACTUAL: 'QC-passed final level BOQ',
    DETAIL_VARIANCE: 'Percentage point variance',
    STATUS: {
      ON_TRACK: 'On track',
      ATTENTION: 'Attention',
      DELAYED: 'Delayed',
      UNMEASURED: 'Unmeasured',
    },
    PROGRESS_DISTRIBUTION_TITLE: 'Progress Distribution',
    PROGRESS_DISTRIBUTION_EMPTY_TITLE: 'Progress distribution unavailable',
    PROGRESS_DISTRIBUTION_EMPTY_DESCRIPTION:
      'No measured progress data is available for this company.',
    REQUIRES_ATTENTION_TITLE: 'Project Requires Attention',
    REQUIRES_ATTENTION_EMPTY_TITLE: 'Nothing to flag',
    REQUIRES_ATTENTION_EMPTY_DESCRIPTION: 'There are no projects requiring attention.',
  },
  PROJECT_PROGRESS: {
    TITLE: 'Project Progress',
    DESCRIPTION: 'Planned, actual, variance, dan status untuk project yang sedang dipilih.',
  },
  COST_BUDGET: {
    TITLE: 'Cost & Budget Performance',
    DESCRIPTION: 'Laporan keuangan dari seluruh project yang dimiliki perusahaan.',
    METRIC_RAB: 'RAB Value',
    DETAIL_RAB: 'Final RAB',
    METRIC_POTENTIAL_MARGIN: 'Potential Margin',
    METRIC_CURRENT_BUDGET: 'Current Budget',
    METRIC_ACTUAL_COST: 'Actual Cost',
    DETAIL_ACTUAL_COST: 'Actual cost against budget',
    METRIC_REMAINING_BUDGET: 'Remaining Budget',
    USED_BADGE: 'used',
    UTILIZATION_TITLE: 'Budget Utilization',
    UTILIZATION_DESCRIPTION: 'Actual cost against current budget.',
  },
  KPI: {
    TITLE: 'Project Performance (KPI)',
    DESCRIPTION: 'Indikator KPI dari seluruh project yang dimiliki perusahaan.',
    METRIC_OVERALL: 'Overall Performance',
    METRIC_SCHEDULE: 'Schedule Performance',
    METRIC_COST: 'Cost Performance',
    METRIC_QUALITY: 'Quality Performance',
    SUPPORTING_SCHEDULE: 'Plan Vs Actual',
    SUPPORTING_COST: 'Cost vs Progress',
    SUPPORTING_QUALITY: 'Inspection Pass Rate',
    STATUS: {
      EXCELLENT: 'Excelent',
      GOOD: 'Good',
      ATTENTION: 'Attention',
      POOR: 'Poor',
      UNMEASURED: 'Unmeasured',
    },
    GAUGE_REMAINING: 'Remaining',
    LEGEND: [
      'Excelent (≥ 95%)',
      'Good (> 90% & < 95%)',
      'Attention (> 80% & < 90%)',
      'Delayed (< 80%)',
    ],
  },
  FINANCE_REMAINING: {
    TITLE: 'Remaining Budget by Project',
    DESCRIPTION: 'Frontend sorts ascending by remaining value to surface risk first.',
    TABLE_PROJECT: 'Project',
    TABLE_BUDGET: 'Budget',
    TABLE_ACTUAL: 'Actual',
    TABLE_REMAINING: 'Remaining',
    TABLE_UTILIZATION: 'Utilization',
    TABLE_EMPTY_TITLE: 'Table is empty',
    TABLE_EMPTY_DESCRIPTION: 'No remaining budget rows were returned for this company.',
    OVERRUN: 'Overrun',
  },
} as const;
