import { type PaymentMethodType } from '../types';

// ============================================================================
// Labels
// ============================================================================

export const PAYMENT_REQUEST_LABELS = {
  LIST: {
    TITLE: 'Payment Requests',
    VIEW_CALENDAR: 'View Calendar',
    SEARCH_PLACEHOLDER: 'Search by code or source...',
    EMPTY: 'No payment requests found.',
    FILTERS: {
      COMPANY: 'Filter by Company',
      STATUS: 'Filter by Status',
      SOURCE_TYPE: 'Filter by Source',
      DATE_RANGE: 'Filter by Date',
      START_DATE: 'Start Date',
      END_DATE: 'End Date',
    },
    COLUMNS: {
      CODE: 'Code',
      SOURCE_TYPE: 'Source',
      AMOUNT: 'Amount (IDR)',
      DUE_DATE: 'Due Date',
      STATUS: 'Status',
      ACTIONS: 'Actions',
    },
    ACTIONS: {
      VIEW: 'Detail',
      PAY: 'Pay',
      CANCEL: 'Cancel',
    },
  },
  PAY_MODAL: {
    TITLE: 'Payment',
    SUBMIT: 'Pay Now',
    PROCESSING: 'Processing...',
    CANCEL: 'Cancel',
    PAYMENT_DATE: 'Payment Date',
    PAYMENT_METHOD: 'Payment Method',
    PAYMENT_AMOUNT: 'Payment Amount',
    TOTAL_AMOUNT: 'Total Amount',
    TRANSFER_VIA: 'Transfer Via',
    TRANSFER_VIA_PLACEHOLDER: 'Masukkan transfer via',
    TRANSFER: 'Transfer',
    GIRO: 'Giro',
    CASH: 'Tunai',
    CHECK_NUMBER: 'Nomor Giro/Cek',
    CHECK_NUMBER_PLACEHOLDER: 'Masukkan nomor giro/cek',
    CHECK_ISSUE_DATE: 'Tanggal Terbit',
    CHECK_EFFECTIVE_DATE: 'Tanggal Efektif',
    NOTES: 'Notes',
    NOTES_PLACEHOLDER: 'Add notes...',
    PAYMENT_PROOF: 'Payment Proof',
    DRAG_DROP: 'Drag & drop files here',
    BROWSE_FILES: 'Browse files',
    DELETE: 'Delete',
    REMOVE_FILE: 'Remove file',
    UPLOAD_DOCUMENT: 'Upload Document',
    DOCUMENT_TYPE: 'Document Type',
    UPLOADING: 'Uploading...',
    PAYMENT_PROOF_REQUIRED: 'Bukti pembayaran wajib diupload',
    PAYMENT_PROOF_REQUIRED_DESC: 'Silakan upload bukti pembayaran terlebih dahulu.',
    MANDATORY_DOCS_INCOMPLETE: 'Dokumen wajib belum lengkap',
    MANDATORY_DOCS_INCOMPLETE_DESC:
      'Silakan upload semua dokumen wajib sebelum melakukan pembayaran.',
    PAY_SUCCESS: 'Pembayaran berhasil',
    PAY_SUCCESS_DESC: 'telah diproses.',
    PAY_FAILED: 'Gagal memproses pembayaran',
  },
  DETAIL: {
    PAGE_TITLE: 'Payment Request Detail',
    NOT_FOUND: 'Payment request not found.',
    INFO: 'Payment Information',
    SOURCE: 'Source Details',
    SOURCE_ITEMS: 'Source Items',
    EVENTS: 'Pembayaran',
    DOCUMENTS: 'Documents',
    STATUS: 'Status',
    AMOUNT: 'Amount',
    PAID_AMOUNT: 'Paid Amount',
    REMAINING: 'Remaining',
    DUE_DATE: 'Due Date',
    SOURCE_CODE: 'Source Code',
    SOURCE_TYPE: 'Source Type',
    REQUEST_TYPE: 'Request Type',
    EMPLOYEE: 'Employee',
    PROJECT: 'Project',
    REASON: 'Reason',
    PAYMENT_METHOD: 'Payment Method',
    NOTES: 'Notes',
    SUBMITTED_AT: 'Submitted At',
    RECEIPT_NO: 'Receipt No.',
    DESCRIPTION: 'Description',
    ITEM_AMOUNT: 'Amount',
    ITEM_NOTES: 'Notes',
    EVENT_ACTION: 'Action',
    EVENT_NOTE: 'Note',
    EVENT_BY: 'By',
    EVENT_AT: 'At',
    GENERAL_INFORMATION: 'General Information',
    COMPANY: 'Company',
    TYPE: 'Type',
    CODE: 'Reference',
    RECIPIENT: 'Recipient',
    PAYMENT_SUMMARY: 'Payment Summary',
    TOTAL_AMOUNT: 'Total Amount',
    PAID: 'Paid',
    PAY_NOW: 'Pay Now',
    CANCEL_PAYMENT: 'Cancel Payment',
    HISTORY_PEMBAYARAN: 'History Pembayaran',
    PROOF_PAYMENT: 'Proof Payment',
    DOWNLOAD: 'Download',
    CLOSE: 'Tutup',
    SUPPORTING_DOCUMENTS: 'Dokumen Pendukung',
    SUPPORTING_DOCUMENT_UPLOAD_TITLE: 'Upload Dokumen',
    SUPPORTING_DOCUMENT_BROWSE_FILE: 'Browse File',
    SUPPORTING_DOCUMENT_BROWSE_FILES: 'Browse files',
    SUPPORTING_DOCUMENT_INVALID_TYPE: 'Format file tidak didukung',
    SUPPORTING_DOCUMENT_INVALID_SIZE: 'Ukuran file melebihi batas',
    SUPPORTING_DOCUMENT_UPLOAD_SUCCESS: 'Dokumen berhasil diunggah',
    SUPPORTING_DOCUMENT_UPLOAD_ERROR: 'Gagal mengunggah dokumen',
    SUPPORTING_DOCUMENT_DELETE_SUCCESS: 'Dokumen berhasil dihapus',
    SUPPORTING_DOCUMENT_DELETE_ERROR: 'Gagal menghapus dokumen',
    SUPPORTING_DOCUMENT_DELETE_LABEL: 'Hapus dokumen',
    SUPPORTING_DOCUMENT_DELETE_CONFIRM_TITLE: 'Konfirmasi Hapus Dokumen',
    SUPPORTING_DOCUMENT_DELETE_CONFIRM_DESCRIPTION:
      'Apakah anda yakin ingin menghapus dokumen ini?',
    SUPPORTING_DOCUMENT_DELETE_CONFIRM_ACTION: 'Ya, Hapus',
    SOURCE_ITEMS_COUNT_SUFFIX: 'Item',
    SOURCE_ITEMS_PERIOD: 'Periode',
    EXPORT: 'Export',
    EXPORT_PDF: 'Export PDF',
    EXPORT_EXCEL: 'Export Excel',
    PAYROLL_DETAIL_TITLE: 'Detail Payroll',
    PAYROLL_DETAIL_COMPONENT: 'Komponen',
    PAYROLL_DETAIL_AMOUNT: 'Jumlah',
    PAYROLL_DETAIL_COMPONENTS_TITLE: 'Komponen Payroll',
    PAYROLL_DETAIL_EMPLOYEE: 'Nama Karyawan',
    PAYROLL_DETAIL_GRADE: 'Golongan',
    PAYROLL_DETAIL_POSITION: 'Jabatan',
    PAYROLL_DETAIL_ACCOUNT: 'Bank & No.Rekening',
    PAYROLL_DETAIL_ACCOUNT_NAME: 'Nama Rekening',
    PAYROLL_DETAIL_PERIOD: 'Periode',
    PAYROLL_DETAIL_NOTE: 'Note',
    PAYROLL_DETAIL_NET_AMOUNT: 'Jumlah Net (THP)',
    TABLE_CATALOG: 'Katalog',
    TABLE_QUANTITY: 'Qty',
    TABLE_UNIT_PRICE: 'Harga Satuan',
    TABLE_TOTAL_AMOUNT: 'Jumlah',
    TABLE_ITEM_NOTES: 'Catatan',
    TABLE_RECEIPT_NUMBER: 'Nota',
    TABLE_DESCRIPTION: 'Description',
    TABLE_PAYROLL_EMPLOYEE: 'Nama Karyawan',
    TABLE_PAYROLL_GRADE: 'Golongan',
    TABLE_PAYROLL_ACCOUNT: 'No.Rekening',
    TABLE_PAYROLL_NET_AMOUNT: 'Jumlah Net (THP)',
    TABLE_ACTION: 'Action',
    ACTION_VIEW: 'Lihat detail',
    PERIOD_SEPARATOR: ' - ',
    WAITING_APPROVAL_MSG:
      'Payment will be processed after receiving approval from the authorized approver.',
    PRE_PAY_CHECK_DEFAULT_MESSAGE: 'Dokumen berikut wajib di-upload sebelum bayar belum lengkap.',
  },
  EDIT_DUE_DATE: {
    TITLE: 'Edit Due Date',
    DATE: 'Date',
    TIME: 'Time',
    CANCEL: 'Batal',
    SAVE: 'Simpan',
    SAVING: 'Menyimpan...',
    DATE_REQUIRED: 'Date is required',
    TIME_REQUIRED: 'Time is required',
  },
  SCHEDULE: {
    TITLE: 'Payment Schedule',
    BACK: 'Back',
    TODAY: 'Today',
    ALL_STATUS: 'Semua Status',
    PAYMENT_REQUESTS_SUFFIX: 'Payment Requests',
    MORE: (count: number) => `+ ${count} more`,
    SOURCE_TYPE_LABELS: {
      purchase_order: 'Purchase Order',
      cost_request: 'Cost Request',
      payroll: 'Payroll',
    },
  },
} as const;

// ============================================================================
// Payment Method Options (for Pay modal)
// ============================================================================

export const PAYMENT_METHOD_OPTIONS: { value: PaymentMethodType; label: string }[] = [
  { value: 'transfer', label: 'Transfer' },
  { value: 'giro', label: 'Giro' },
  { value: 'cash', label: 'Tunai' },
];
