import { COMMON_LABELS, COMMON_STATUS_OPTIONS } from '@/shared/constants';

export const WAREHOUSE_LABELS = {
  LIST: {
    TITLE: 'Warehouse',
    DESCRIPTION: 'Manage warehouses in the system',
    ADD_BUTTON: 'Tambah Warehouse Baru',
    EMPTY: 'Tidak ada warehouse ditemukan',
    COLUMNS: {
      CODE: COMMON_LABELS.FIELDS.CODE,
      NAME: 'Nama Warehouse',
      TYPE: 'Type',
      COMPANY: 'Company',
      WORK_START_TIME: 'Jam Mulai',
      WORK_END_TIME: 'Jam Selesai',
      STATUS: COMMON_LABELS.FIELDS.STATUS,
      ACTIONS: COMMON_LABELS.FIELDS.ACTIONS,
    },
    STATUS: COMMON_LABELS.STATUS,
    ACTIONS: COMMON_LABELS.LIST.ACTIONS,
    FILTERS: {
      STATUS: COMMON_LABELS.FIELDS.STATUS,
    },
  },
  CREATE: {
    PAGE_TITLE: 'Buat Warehouse Baru',
    BACK_BUTTON: COMMON_LABELS.ACTIONS.BACK,
    FIELDS: {
      CODE: `${COMMON_LABELS.FIELDS.CODE} Warehouse`,
      NAME: `${COMMON_LABELS.FIELDS.NAME} Warehouse`,
      TYPE: 'Type Warehouse',
      COMPANY: 'Company',
      STATUS: COMMON_LABELS.FIELDS.STATUS,
      WORK_START_TIME: 'Jam Mulai',
      WORK_END_TIME: 'Jam Selesai',
      WORK_DAYS: 'Hari Kerja',
      PROVINCE: 'Provinsi',
      CITY: 'Kota',
      DISTRICT: 'Kecamatan',
      VILLAGE: 'Desa',
      ADDRESS_DETAIL: 'Detail Alamat',
      LATITUDE: 'Latitude',
      LONGITUDE: 'Longitude',
      ATTENDANCE_RADIUS: 'Radius Absensi (meter)',
      TIMEZONE: 'Zona Waktu',
      ADDRESS_SECTION: 'Informasi Alamat',
    },
    BUTTONS: {
      CANCEL: COMMON_LABELS.ACTIONS.CANCEL,
      SAVE: COMMON_LABELS.ACTIONS.SAVE,
      SAVING: COMMON_LABELS.STATE.SAVING,
    },
    DIALOG: {
      TITLE: 'Simpan Warehouse Baru?',
      DESCRIPTION: 'Anda akan membuat warehouse baru dengan data yang telah ditentukan.',
      CANCEL: COMMON_LABELS.ACTIONS.CANCEL,
      CONFIRM: COMMON_LABELS.ACTIONS.SAVE,
    },
  },
  EDIT: {
    PAGE_TITLE: 'Edit Warehouse',
    BACK_BUTTON: COMMON_LABELS.ACTIONS.BACK,
    NOT_FOUND: 'Warehouse tidak ditemukan',
    FIELDS: {
      CODE: COMMON_LABELS.FIELDS.CODE,
      NAME: COMMON_LABELS.FIELDS.NAME,
      TYPE: 'Type',
      COMPANY: 'Company',
      STATUS: COMMON_LABELS.FIELDS.STATUS,
      WORK_START_TIME: 'Jam Mulai',
      WORK_END_TIME: 'Jam Selesai',
      WORK_DAYS: 'Hari Kerja',
      PROVINCE: 'Provinsi',
      CITY: 'Kota',
      DISTRICT: 'Kecamatan',
      VILLAGE: 'Desa',
      ADDRESS_DETAIL: 'Detail Alamat',
      LATITUDE: 'Latitude',
      LONGITUDE: 'Longitude',
      ATTENDANCE_RADIUS: 'Radius Absensi (meter)',
      TIMEZONE: 'Zona Waktu',
      ADDRESS_SECTION: 'Informasi Alamat',
    },
    BUTTONS: {
      CANCEL: COMMON_LABELS.ACTIONS.CANCEL,
      SAVE: COMMON_LABELS.ACTIONS.SAVE_CHANGE,
      SAVING: COMMON_LABELS.STATE.SAVING,
    },
    DIALOG: {
      TITLE: 'Simpan Perubahan?',
      DESCRIPTION: 'Anda akan menyimpan perubahan pada warehouse ini.',
      CANCEL: COMMON_LABELS.ACTIONS.CANCEL,
      CONFIRM: COMMON_LABELS.ACTIONS.SAVE,
    },
  },
  FORM: {
    TITLE: 'Warehouse',
  },
  DIALOG: {
    DELETE_TITLE: 'Delete Warehouse',
    DELETE_DESCRIPTION: 'Are you sure you want to delete this warehouse?',
  },
  DETAIL: {
    PAGE_TITLE: 'Detail Warehouse',
    FIELDS: {
      CODE: COMMON_LABELS.FIELDS.CODE,
      NAME: 'Nama Warehouse',
      TYPE: 'Type',
      COMPANY: 'Company',
      STATUS: COMMON_LABELS.FIELDS.STATUS,
      WORK_START_TIME: 'Jam Mulai',
      WORK_END_TIME: 'Jam Selesai',
      PROVINCE: 'Provinsi',
      CITY: 'Kota',
      DISTRICT: 'Kecamatan',
      VILLAGE: 'Desa',
      ADDRESS_DETAIL: 'Detail Alamat',
      LATITUDE: 'Latitude',
      LONGITUDE: 'Longitude',
      ATTENDANCE_RADIUS: 'Radius Absensi (meter)',
      TIMEZONE: 'Zona Waktu',
    },
    STATUS_ACTIVE: COMMON_LABELS.STATUS.ACTIVE,
    STATUS_INACTIVE: COMMON_LABELS.STATUS.INACTIVE,
    BUTTONS: {
      EDIT: COMMON_LABELS.ACTIONS.EDIT,
      CLOSE: COMMON_LABELS.ACTIONS.CANCEL,
    },
    DIALOG: {
      CHANGE_STATUS_TITLE: COMMON_LABELS.DIALOG.CHANGE_STATUS_TITLE,
      CHANGE_STATUS_DESCRIPTION: 'Anda akan mengubah status warehouse ini.',
      CHANGE_STATUS_CANCEL: COMMON_LABELS.ACTIONS.CANCEL,
      CHANGE_STATUS_CONFIRM: COMMON_LABELS.ACTIONS.SAVE,
    },
  },
} as const;

export const STATUS_OPTIONS = COMMON_STATUS_OPTIONS;

export const PLACEHOLDERS = {
  CODE: 'Masukan kode',
  NAME: 'Masukan nama warehouse',
  TYPE: 'Pilih type warehouse',
  COMPANY: 'Pilih company',
  STATUS: COMMON_LABELS.PLACEHOLDERS.STATUS,
  WORK_START_TIME: '08:00',
  WORK_END_TIME: '17:00',
  PROVINCE: 'Pilih provinsi',
  CITY: 'Pilih kota',
  DISTRICT: 'Pilih kecamatan',
  VILLAGE: 'Pilih desa',
  ADDRESS_DETAIL: 'Tulis detail alamat disini',
  LATITUDE: '0',
  LONGITUDE: '0',
  ATTENDANCE_RADIUS: '100',
} as const;
