import { COMMON_LABELS } from '@/shared/constants';

export const VENDOR_CATALOG_LABELS = {
  LIST: {
    TITLE: 'Vendor Catalog',
    DESCRIPTION: 'Kelola data vendor dalam sistem',
    ADD_BUTTON: 'Tambah Vendor Baru',
    EMPTY: 'Vendor tidak ditemukan',
    COLUMNS: {
      CODE: COMMON_LABELS.FIELDS.CODE,
      NAME: 'Nama',
      TYPE: 'Tipe',
      STATUS: COMMON_LABELS.FIELDS.STATUS,
      ACTIONS: COMMON_LABELS.FIELDS.ACTIONS,
    },
    STATUS: COMMON_LABELS.STATUS,
    ACTIONS: COMMON_LABELS.LIST.ACTIONS,
    FILTERS: {
      STATUS: 'Semua Status',
    },
  },
  CREATE: {
    PAGE_TITLE: 'Buat Vendor Baru',
    BACK_BUTTON: COMMON_LABELS.ACTIONS.BACK,
    FIELDS: {
      CODE: 'Kode Vendor',
      NAME: 'Nama',
      TYPE: 'Tipe Vendor',
      ADDRESS_SECTION: 'Informasi Detail Alamat',
      VENDOR_SUBCONTRACTOR: 'Vendor Subcontractor',
      VENDOR_SUPPLIER: 'Vendor Supplier',
      VENDOR_LOGISTIC: 'Vendor Logistic',
      NPWP: 'NPWP',
      SIUP: 'No. SIUP',
      PHONE: 'Telepon',
      EMAIL: 'Email',
      PROVINCE: 'Provinsi',
      CITY: 'Kota',
      DISTRICT: 'Kecamatan',
      VILLAGE: 'Desa',
      POSTAL_CODE: 'Kode Pos',
      ADDRESS: 'Detail Alamat',
      PIC_NAME: 'Nama PIC',
      PIC_PHONE: 'No. Telepon PIC',
      PIC_EMAIL: 'Email PIC',
      BANK_NAME: 'Nama Bank',
      BANK_ACCOUNT: 'No. Rekening',
      BANK_HOLDER: 'Atas Nama',
      NOTES: 'Catatan',
      STATUS: COMMON_LABELS.FIELDS.STATUS,
      STATUS_PLACEHOLDER: COMMON_LABELS.PLACEHOLDERS.STATUS,
    },
    BUTTONS: {
      CANCEL: COMMON_LABELS.ACTIONS.CANCEL,
      SAVE: COMMON_LABELS.ACTIONS.SAVE,
      SAVING: COMMON_LABELS.STATE.SAVING,
    },
    DIALOG: {
      TITLE: 'Simpan Vendor Baru?',
      DESCRIPTION: 'Anda akan membuat vendor baru dengan data yang telah ditentukan.',
      CANCEL: COMMON_LABELS.ACTIONS.CANCEL,
      CONFIRM: COMMON_LABELS.ACTIONS.SAVE,
    },
  },
  EDIT: {
    PAGE_TITLE: 'Edit Vendor',
    BACK_BUTTON: COMMON_LABELS.ACTIONS.BACK,
    NOT_FOUND: 'Vendor tidak ditemukan',
    FIELDS: {
      CODE: 'Kode Vendor',
      NAME: 'Nama',
      TYPE: 'Tipe Vendor',
      NPWP: 'NPWP',
      SIUP: 'No. SIUP',
      PHONE: 'Telepon',
      EMAIL: 'Email',
      PROVINCE: 'Provinsi',
      CITY: 'Kota',
      DISTRICT: 'Kecamatan',
      VILLAGE: 'Desa',
      POSTAL_CODE: 'Kode Pos',
      ADDRESS: 'Detail Alamat',
      PIC_NAME: 'Nama PIC',
      PIC_PHONE: 'No. Telepon PIC',
      PIC_EMAIL: 'Email PIC',
      BANK_NAME: 'Nama Bank',
      BANK_ACCOUNT: 'No. Rekening',
      BANK_HOLDER: 'Atas Nama',
      NOTES: 'Catatan',
      STATUS: COMMON_LABELS.FIELDS.STATUS,
    },
    BUTTONS: {
      CANCEL: COMMON_LABELS.ACTIONS.CANCEL,
      SAVE: COMMON_LABELS.ACTIONS.SAVE_CHANGE,
      SAVING: COMMON_LABELS.STATE.SAVING,
    },
    DIALOG: {
      TITLE: 'Simpan Perubahan?',
      DESCRIPTION: 'Anda akan menyimpan perubahan pada vendor ini.',
      CANCEL: COMMON_LABELS.ACTIONS.CANCEL,
      CONFIRM: COMMON_LABELS.ACTIONS.SAVE,
    },
  },
  DIALOG: {
    DELETE_TITLE: 'Hapus Vendor',
    DELETE_DESCRIPTION: 'Apakah Anda yakin ingin menghapus vendor ini?',
  },
  DETAIL: {
    PAGE_TITLE: 'Detail Vendor',
    BACK_BUTTON: COMMON_LABELS.ACTIONS.BACK,
    NOT_FOUND: 'Vendor tidak ditemukan',
    DELETE_BUTTON: COMMON_LABELS.ACTIONS.DELETE,
    INFO_CARD_TITLE: 'Informasi Vendor',
    EDIT_BUTTON: COMMON_LABELS.ACTIONS.EDIT,
    STATUS_ACTIVE: COMMON_LABELS.STATUS.ACTIVE,
    STATUS_INACTIVE: COMMON_LABELS.STATUS.INACTIVE,
    FIELDS: {
      CODE: 'Kode',
      NAME: 'Nama',
      TYPE: 'Type Vendor',
      RATING: 'Rating',
      RATING_TOTAL: 'Total Rating',
      RATING_LAST: 'Terakhir Rating',
      NPWP: 'NPWP',
      SIUP: 'No. SIUP',
      PHONE: 'Telepon',
      EMAIL: 'Email',
      PROVINCE: 'Provinsi',
      CITY: 'Kota',
      DISTRICT: 'Kecamatan',
      VILLAGE: 'Desa',
      POSTAL_CODE: 'Kode Pos',
      ADDRESS: 'Detail Alamat',
      PIC_NAME: 'Nama PIC',
      PIC_PHONE: 'No. Telepon PIC',
      PIC_EMAIL: 'Email PIC',
      BANK_NAME: 'Nama Bank',
      BANK_ACCOUNT: 'No. Rekening',
      BANK_HOLDER: 'Atas Nama',
      NOTES: 'Catatan',
      STATUS: 'Status',
    },
    BUTTONS: {
      EDIT: COMMON_LABELS.ACTIONS.EDIT,
      CLOSE: COMMON_LABELS.ACTIONS.CANCEL,
    },
    DIALOG: {
      CHANGE_STATUS_TITLE: COMMON_LABELS.DIALOG.CHANGE_STATUS_TITLE,
      CHANGE_STATUS_DESCRIPTION: 'Anda akan mengubah status vendor ini.',
      CHANGE_STATUS_CANCEL: COMMON_LABELS.ACTIONS.CANCEL,
      CHANGE_STATUS_CONFIRM: COMMON_LABELS.ACTIONS.SAVE,
    },
  },
  RATING: {
    TITLE: 'Rating',
    SUMMARY_TITLE: 'Ringkasan Rating',
    HISTORY_TITLE: 'Riwayat Rating',
    EMPTY: 'Belum ada rating untuk vendor ini.',
    EMPTY_FILTERED: 'Tidak ada rating yang sesuai pencarian.',
    SEARCH: 'Cari rating',
    COLUMNS: {
      INFO_PO: 'Info PO',
      DATE: 'Tanggal Rating',
      SOURCE: 'Info PO',
      RATED_BY: 'Dinilai Oleh',
      SCORE: 'Overall Score',
      ACTIONS: COMMON_LABELS.FIELDS.ACTIONS,
    },
    SUMMARY: {
      LAST_RATED_AT: 'Terakhir dinilai',
    },
  },
  ITEM_CATALOG: {
    TITLE: 'Item Catalog',
    ADD_BUTTON: 'Tambah Baris',
    EMPTY: 'Item catalog tidak ditemukan',
    COLUMNS: {
      CODE: COMMON_LABELS.FIELDS.CODE,
      NAME: 'Nama Item',
      PRICE: 'Harga',
      UOM: 'UoM',
      STATUS: COMMON_LABELS.FIELDS.STATUS,
      ACTIONS: COMMON_LABELS.FIELDS.ACTIONS,
    },
    STATUS_OPTIONS: [
      { label: COMMON_LABELS.STATUS.ACTIVE, value: 'true' },
      { label: COMMON_LABELS.STATUS.INACTIVE, value: 'false' },
    ],
    PLACEHOLDERS: {
      PRICE: '0',
    },
    MESSAGES: {
      UNSAVED: 'Ada perubahan belum disimpan',
      VALIDATION_FAILED: 'Beberapa baris belum valid. Periksa kembali data Anda.',
      SAVE_ERROR: 'Sebagian perubahan gagal disimpan. Coba lagi.',
      ROW_NEW: 'Baru',
    },
    BUTTONS: {
      SAVE_ALL: 'Simpan',
      CANCEL_DRAFTS: 'Batal',
      SAVING: 'Menyimpan...',
      ADD_ROW: 'Tambah',
      LOAD_MORE: 'Muat Lebih Banyak',
      DOWNLOAD_TEMPLATE: 'Download Template',
      IMPORT: 'Import',
    },
    IMPORT_EXPORT: {
      TOAST_DOWNLOAD_ID: 'vendor-item-catalog-download',
      TOAST_IMPORT_ID: 'vendor-item-catalog-import',
      FILE_NAME: 'item-catalog-template.xlsx',
      MESSAGES: {
        DOWNLOAD_PROGRESS: (percent: number) => `Mengunduh template... ${percent}%`,
        DOWNLOAD_SUCCESS: 'Template berhasil diunduh',
        DOWNLOAD_ERROR: 'Gagal mengunduh template',
        IMPORT_PROGRESS: (percent: number) => `Mengupload file... ${percent}%`,
        IMPORT_PROCESSING: 'Memproses data...',
        IMPORT_SUCCESS: (count: number) => `${count} baris berhasil diimport`,
        IMPORT_FAILED: (count: number) => `${count} baris gagal diimport`,
        IMPORT_ERROR: 'Gagal mengimport data',
      },
    },
    ACTIONS: {
      DELETE: COMMON_LABELS.LIST.ACTIONS.DELETE,
      RESTORE: 'Pulihkan',
    },
    CONTEXT_MENU: {
      COPY: 'Salin',
      PASTE: 'Tempel',
      DELETE_ROW: 'Hapus',
      ROWS_SUFFIX: 'baris',
    },
  },
  CAPABILITY: {
    TITLE: 'Capabilities',
    ADD_BUTTON: 'Tambah',
    EMPTY: 'Capability tidak ditemukan',
    COLUMNS: {
      CODE: COMMON_LABELS.FIELDS.CODE,
      NAME: 'Nama Skill',
      STATUS: COMMON_LABELS.FIELDS.STATUS,
      ACTIONS: COMMON_LABELS.FIELDS.ACTIONS,
    },
    ACTIONS: {
      EDIT: COMMON_LABELS.LIST.ACTIONS.EDIT,
      DELETE: COMMON_LABELS.LIST.ACTIONS.DELETE,
    },
    DIALOG: {
      DELETE_TITLE: 'Hapus Capability',
      DELETE_DESCRIPTION: 'Apakah Anda yakin ingin menghapus capability ini?',
      CHANGE_STATUS_TITLE: COMMON_LABELS.DIALOG.CHANGE_STATUS_TITLE,
      CHANGE_STATUS_DESCRIPTION: 'Anda akan mengubah status capability ini.',
      CHANGE_STATUS_CANCEL: COMMON_LABELS.ACTIONS.CANCEL,
      CHANGE_STATUS_CONFIRM: COMMON_LABELS.ACTIONS.SAVE,
    },
    DRAWER: {
      ADD_TITLE: 'Tambah Capability',
      EDIT_TITLE: 'Edit Capability',
      FIELDS: {
        SKILL: 'Skill',
        STATUS: 'Status',
      },
      PLACEHOLDERS: {
        SKILL: 'Pilih skill',
      },
      BUTTONS: {
        SAVE: COMMON_LABELS.ACTIONS.SAVE,
        CANCEL: COMMON_LABELS.ACTIONS.CANCEL,
        SAVING: COMMON_LABELS.STATE.SAVING,
      },
    },
  },
  SERVICE_COVERAGE: {
    TITLE: 'Service Coverage',
    ADD_BUTTON: 'Setting',
    EMPTY: 'Service coverage tidak ditemukan',
    COLUMNS: {
      PROVINCE: 'Provinsi',
      CITY: 'Kabupaten/Kota',
    },
    DRAWER: {
      TITLE: 'Tambah Service Coverage',
      COVERAGE_LABEL: 'Coverage',
      FIELDS: {
        PROVINCE: 'Provinsi',
        CITY: 'Kabupaten/Kota',
      },
      PLACEHOLDERS: {
        PROVINCE: 'Pilih provinsi',
        CITY: 'Semua Kabupaten/Kota',
      },
      BUTTONS: {
        SAVE: COMMON_LABELS.ACTIONS.SAVE,
        CANCEL: COMMON_LABELS.ACTIONS.CANCEL,
        SAVING: COMMON_LABELS.STATE.SAVING,
        ADD_COVERAGE: 'Tambah Coverage',
      },
    },
  },
  OFFERING_DOCUMENT: {
    TITLE: 'Offering Documents',
    ADD_BUTTON: 'Tambah',
    EMPTY: 'Offering document tidak ditemukan',
    COLUMNS: {
      CODE: 'Kode',
      TITLE: 'Nama Document',
      PERIOD: 'Periode',
      UPDATED_AT: 'Tanggal Update',
      STATUS: COMMON_LABELS.FIELDS.STATUS,
      ACTIONS: COMMON_LABELS.FIELDS.ACTIONS,
    },
    ACTIONS: {
      EDIT: COMMON_LABELS.LIST.ACTIONS.EDIT,
      DELETE: COMMON_LABELS.LIST.ACTIONS.DELETE,
    },
    DIALOG: {
      DELETE_TITLE: 'Hapus Offering Document',
      DELETE_DESCRIPTION: 'Apakah Anda yakin ingin menghapus offering document ini?',
      CHANGE_STATUS_TITLE: COMMON_LABELS.DIALOG.CHANGE_STATUS_TITLE,
      CHANGE_STATUS_DESCRIPTION: 'Anda akan mengubah status offering document ini.',
      CHANGE_STATUS_CANCEL: COMMON_LABELS.ACTIONS.CANCEL,
      CHANGE_STATUS_CONFIRM: COMMON_LABELS.ACTIONS.SAVE,
    },
    DRAWER: {
      ADD_TITLE: 'Tambah Offering Document',
      EDIT_TITLE: 'Edit Offering Document',
      FIELDS: {
        CODE: 'Kode',
        TITLE: 'Nama Document',
        PERIOD_START: 'Tanggal Mulai',
        PERIOD_END: 'Tanggal Akhir',
        DESCRIPTION: 'Deskripsi',
        STATUS: 'Status',
      },
      PLACEHOLDERS: {
        CODE: 'Masukan kode document',
        TITLE: 'Masukan nama document',
        PERIOD_START: 'Pilih tanggal mulai',
        PERIOD_END: 'Pilih tanggal akhir',
        DESCRIPTION: 'Masukan deskripsi',
      },
      BUTTONS: {
        SAVE: COMMON_LABELS.ACTIONS.SAVE,
        CANCEL: COMMON_LABELS.ACTIONS.CANCEL,
        SAVING: COMMON_LABELS.STATE.SAVING,
      },
    },
  },
  FLEET: {
    TITLE: 'Fleet',
    ADD_BUTTON: 'Tambah',
    EMPTY: 'Fleet tidak ditemukan',
    COLUMNS: {
      NAME: 'Nama Armada',
      CODE: 'Kode',
      VEHICLE_TYPE: 'Type',
      PLATE_NUMBER: 'Plat Nomor',
      STATUS: COMMON_LABELS.FIELDS.STATUS,
      ACTIONS: COMMON_LABELS.FIELDS.ACTIONS,
    },
    ACTIONS: {
      EDIT: COMMON_LABELS.LIST.ACTIONS.EDIT,
      DELETE: COMMON_LABELS.LIST.ACTIONS.DELETE,
    },
    DIALOG: {
      DELETE_TITLE: 'Hapus Fleet',
      DELETE_DESCRIPTION: 'Apakah Anda yakin ingin menghapus fleet ini?',
      CHANGE_STATUS_TITLE: COMMON_LABELS.DIALOG.CHANGE_STATUS_TITLE,
      CHANGE_STATUS_DESCRIPTION: 'Anda akan mengubah status fleet ini.',
      CHANGE_STATUS_CANCEL: COMMON_LABELS.ACTIONS.CANCEL,
      CHANGE_STATUS_CONFIRM: COMMON_LABELS.ACTIONS.SAVE,
    },
    DRAWER: {
      ADD_TITLE: 'Tambah Fleet',
      EDIT_TITLE: 'Edit Fleet',
      FIELDS: {
        NAME: 'Nama Armada',
        CODE: 'Kode',
        VEHICLE_TYPE: 'Type',
        PLATE_NUMBER: 'Plat Nomor',
        STATUS: 'Status',
      },
      PLACEHOLDERS: {
        NAME: 'Masukan nama armada',
        CODE: 'Masukan kode armada',
        VEHICLE_TYPE: 'Pilih type',
        PLATE_NUMBER: 'Masukan plat kendaraan',
      },
      BUTTONS: {
        SAVE: COMMON_LABELS.ACTIONS.SAVE,
        CANCEL: COMMON_LABELS.ACTIONS.CANCEL,
        SAVING: COMMON_LABELS.STATE.SAVING,
      },
    },
  },
} as const;

export const VENDOR_CATALOG_PLACEHOLDERS = {
  CODE: 'Masukan kode',
  NAME: 'Masukan nama vendor',
  NPWP: 'Masukan NPWP',
  SIUP: 'Masukan No. SIUP',
  PHONE: 'Masukan nomor telepon',
  EMAIL: 'Masukan alamat email',
  PROVINCE: 'Pilih provinsi',
  CITY: 'Pilih kota',
  DISTRICT: 'Pilih kecamatan',
  VILLAGE: 'Pilih desa',
  POSTAL_CODE: 'Masukan kode pos',
  ADDRESS: 'Tulis detail alamat disini',
  PIC_NAME: 'Masukan nama PIC',
  PIC_PHONE: 'Masukan nomor telepon PIC',
  PIC_EMAIL: 'Masukan email PIC',
  BANK_NAME: 'Masukan nama bank',
  BANK_ACCOUNT: 'Masukan nomor rekening',
  BANK_HOLDER: 'Masukan atas nama',
  NOTES: 'Masukan catatan',
} as const;

export const BOOLEAN_OPTIONS = [
  { label: 'Ya', value: 'true' },
  { label: 'Tidak', value: 'false' },
];
