export const TAX_FILING_LABELS = {
  LIST: {
    TITLE: 'Tax Filing',
    SEARCH_PLACEHOLDER: 'Pencarian',
    EMPTY: 'No tax filing found.',
    FILTERS: {
      COMPANY: 'Company 01',
      PERIOD: 'Tax Period',
      TAX_TYPE: 'All Tax Type',
      STATUS: 'All Status',
    },
    COLUMNS: {
      CODE: 'Code',
      TAX_PERIOD: 'Tax Period',
      TAX_TYPE: 'Tax Type',
      TOTAL_TAX: 'Total Tax',
      DUE_DATE: 'Due Date',
      STATUS: 'Status',
      ACTION: 'Action',
    },
    ACTIONS: { VIEW: 'View', OPEN_MENU: 'Open tax filing actions' },
  },
  DETAIL: {
    TITLE: 'Tax Filing Detail',
    NOT_FOUND: 'Tax filing not found.',
    LOAD_ERROR: 'Failed to load tax filing.',
    SUMMARY: 'Tax Summary',
    TRANSACTIONS: 'Tax Transaction Details',
    PAYMENTS: 'Payments',
    INFORMATION: 'Filing Information',
    ATTACHMENTS: 'Attachments',
    ADD_PAYMENT: 'Add Payment',
    EDIT_PAYMENT: 'Edit Payment',
    DETAIL_PAYMENT: 'Payment Detail',
    SET_INFORMATION: 'Set Filing Information',
    UPLOAD_DOCUMENT: 'Upload Document',
    DELETE: 'Delete',
    CLOSE: 'Close',
    SAVE: 'Save',
    BACK: 'Back',
    EMPTY: 'No data.',
    EMPTY_ATTACHMENTS: 'No attachments.',
    ATTACHMENT_SUBTITLE: 'Lain-lain',
    ATTACHMENT_ADD_FILES: 'Add files',
    ATTACHMENT_UPLOADING: 'Uploading files...',
    ATTACHMENT_DELETE: (fileName: string) => `Delete ${fileName}`,
    DOWNLOAD_ATTACHMENT: (fileName: string) => `Download ${fileName}`,
  },
  FIELDS: {
    TAX_PAYABLE: 'Tax Payable',
    TAX_PAID: 'Tax Paid',
    OUTSTANDING: 'Outstanding',
    BILLING_CODE: 'Billing Code',
    PAYMENT_DATE: 'Payment Date',
    PAYMENT_TYPE_ID: 'Payment Type ID',
    AMOUNT_PAID: 'Amount Paid',
    NTPN: 'NTPN',
    SUBMITTED_BY: 'Submitted By',
    PAYMENT_STATUS: 'Payment Status',
    BPE_NUMBER: 'BPE Number',
    BPE_DATE: 'BPE Date',
    DJP_REFERENCE_NO: 'DJP Reference No',
    STATUS: 'Status',
    FILES: 'Files',
  },
} as const;
export const TAX_FILING_STATUS_OPTIONS = [
  { value: 'reported', label: 'Reported' },
  { value: 'not_reported', label: 'Not Reported' },
  { value: 'in_progress', label: 'In Progress' },
  { value: 'closed', label: 'Closed' },
];
export const TAX_FILING_STATUS_LABELS: Record<string, string> = Object.fromEntries(
  TAX_FILING_STATUS_OPTIONS.map((x) => [x.value, x.label])
);
